### ISSUE TITLE
Error running with python 3.8 on macOS Big Sur 11.2.2

### ISSUE THREAD

**Issue by troehling** [CFEL-CMI/pymepix-viewer#2]
I am running with python 3.7 and everything works fine. Switching to python 3.8 gives me an error when running `pythonviewer`.

Operating System: macOS Big Sur 11.2.2
conda version: 4.9.2
python version: 3.8.8

I took the following steps before running the viewer:
`# clone pymepix and pymepix-viewer repositories (branch: develop)
conda create -n py3.8 python=3.8
conda activate py3.8
conda install pyqtgraph 
conda install scikit-learn
conda install pyserial
conda install pyqt
conda install pyzmq
conda install h5py

Cd pymepix
Python setup.py develop
Cd pymepix-viewer 
Python setup.py develop`

After this installation process, running pymepixviewer lead to the following error:
`Traceback (most recent call last):
  File "/Users/roehlint/miniconda3/envs/py3.8/bin/pymepixviewer", line 33, in <module>
    sys.exit(load_entry_point('pymepixviewer', 'console_scripts', 'pymepixviewer')())
  File "/Users/roehlint/Documents/pymepix/pymepix-viewer/pymepixviewer/main.py", line 453, in main
    config = PymepixDAQ()
  File "/Users/roehlint/Documents/pymepix/pymepix-viewer/pymepixviewer/main.py", line 102, in __init__
    self.startupTimepix()
  File "/Users/roehlint/Documents/pymepix/pymepix-viewer/pymepixviewer/main.py", line 150, in startupTimepix
    self._timepix.start()
  File "/Users/roehlint/Documents/pymepix/pymepix/pymepix/pymepix.py", line 226, in start
    t.start()
  File "/Users/roehlint/Documents/pymepix/pymepix/pymepix/timepixdevice.py", line 295, in start
    self._acquisition_pipeline.start()
  File "/Users/roehlint/Documents/pymepix/pymepix/pymepix/processing/baseacquisition.py", line 242, in start
    s.start()
  File "/Users/roehlint/Documents/pymepix/pymepix/pymepix/processing/baseacquisition.py", line 146, in start
    p.start()
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'memoryview' object
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/roehlint/Documents/pymepix/pymepix/pymepix/core/log.py", line 69, in _logging_thread
    name, log_level, message, args, kwargs = log_queue.get()
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/queues.py", line 97, in get
    res = self._recv_bytes()
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/roehlint/miniconda3/envs/py3.8/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError`

**Comment by troehling** [comment]
Closing because I assume this issue is outdated right now.
